### ISSUE TITLE
Dead link in wiki

### ISSUE THREAD

**Issue by andrew-gaston** [cdibbs/linq2ldap#1]
**Link to the wiki page and section:**
https://github.com/cdibbs/linq2ldap/wiki/Code-Reuse-And-Testing#expression-reuse

**The dead link:**
https://github.com/cdibbs/linq2ldap.core/blob/master/Linq2Ldap.Core/Specification.cs#L42

**Comment by cdibbs** [comment]
Fixed. Thanks for pointing that out!
